export const formatCurrency: any;
export const getCurrencySymbol: any;
export const formatCompactCurrency: any;
export const formatDate: any;
export const formatDateTime: any;
export const formatRelativeTime: any;
export const formatNumber: any;
export const formatPercentage: any;
export const useFormatters: any;
declare const _: any;
export default _;
