name: Deploy People Connect Frontend

on:
  push:
    branches: [develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    uses: Neonbee-ai/neonbee-devops/.github/workflows/neonbee-deploy-vite-mfe.yml@main
    with:
      service_name: people-connect-fe
      nginx_root_dev: /var/www/dev-cdn.skyoffice360.com/html/people-connect
      nginx_root_staging: /var/www/staging.people.skyoffice360.com/html
      vite_base_url_dev: https://dev-cdn.skyoffice360.com/people-connect/
      vite_base_url_staging: https://staging.people.skyoffice360.com/
      is_mfe: true
    secrets: inherit
